# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-03-07 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=30)),
                ('area', models.IntegerField()),
                ('no_of_roads', models.IntegerField()),
                ('no_of_trees', models.IntegerField()),
                ('no_of_shops', models.IntegerField()),
                ('no_of_schools', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=30)),
                ('area', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=30)),
                ('area', models.IntegerField()),
                ('no_of_hospital', models.IntegerField()),
                ('no_of_nationalparks', models.IntegerField()),
                ('no_of_rivers', models.IntegerField()),
                ('no_of_schools', models.IntegerField()),
                ('continent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vectorassignment.Continent')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vectorassignment.Country'),
        ),
    ]
