# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-03-08 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorassignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='no_of_roads',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='no_of_schools',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='no_of_shops',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='no_of_trees',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='continent',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='continent',
            name='population',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='no_of_hospital',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='no_of_nationalparks',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='no_of_rivers',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='no_of_schools',
            field=models.CharField(max_length=100),
        ),
    ]
